language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as test
before_script:
  - echo "no test"

#  Build and Tagging
script:
  - docker --version # print the version for logging
  - docker build -t bvgo/udagram-api-feed:latest ./udagram-api-feed
  - docker build -t bvgo/udagram-api-user:latest ./udagram-api-user
  - docker build -t bvgo/udagram-frontend:latest ./udagram-frontend
  - docker build -t bvgo/reverseproxy:latest ./udagram-reverseproxy

# Push to DockerHub
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bvgo/udagram-api-feed
  - docker push bvgo/udagram-api-user
  - docker push bvgo/udagram-frontend
  - docker push bvgo/reverseproxy
